# This file was generated by GoReleaser. DO NOT EDIT.
cask "simbeamd" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "90cbe28e40ff9510b29b54c6664a988436dd7fd7155a306ab84d8a9be4346bd7"
      url "https://github.com/kei-sidorov/simbeam/releases/download/v#{version}/simbeamd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5a83993fdc203c9ea00d6647adee3b80a1b661b819ec3e4394badd7860a87f7c"
      url "https://github.com/kei-sidorov/simbeam/releases/download/v#{version}/simbeamd_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "simbeamd"
  desc "simbeam daemon — stream an iOS simulator from Mac to iPad"
  homepage "https://github.com/kei-sidorov/simbeam"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "kei-sidorov/simbeam/simbeam-control",
    ]

  binary "simbeamd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/simbeamd"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    simbeamd is shipped as an unsigned binary. The cask's post-install hook
    strips the macOS quarantine attribute so Gatekeeper should not block it.
    simbeamd drives simulators through simbeam-control (needs a full Xcode);
    idb_companion and ffmpeg are no longer required.
  EOS
end
