# This file was generated by GoReleaser. DO NOT EDIT.
cask "simbeamd" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "49d269e02e9fa45e3c42a280302426d396d77b3a3c5ea7f293dd7949763bfbb3"
      url "https://github.com/kei-sidorov/simbeam/releases/download/v#{version}/simbeamd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7a7c46b5724a77e2df5bdece932b100c694b57ac71a5a9899a4dc3f3de6e3f18"
      url "https://github.com/kei-sidorov/simbeam/releases/download/v#{version}/simbeamd_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "simbeamd"
  desc "simbeam daemon — stream an iOS simulator from Mac to iPad"
  homepage "https://github.com/kei-sidorov/simbeam"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "facebook/fb/idb-companion",
      "ffmpeg",
    ]

  binary "simbeamd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/simbeamd"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    simbeamd is shipped as an unsigned binary. The cask's post-install hook
    strips the macOS quarantine attribute so Gatekeeper should not block it.
    simbeamd shells out to idb_companion (simulators) and ffmpeg (h264_videotoolbox).

    idb_companion comes from Meta's tap. If install fails to find it, run:
      brew tap facebook/fb
  EOS
end
