# This file was generated by GoReleaser. DO NOT EDIT.
cask "simbeamd" do
  version "0.10.1"

  on_macos do
    on_intel do
      sha256 "097d3ddd2450354399021a13a79621e435221e5508ec2e81452733c5a390a8b1"
      url "https://github.com/kei-sidorov/simbeam/releases/download/v#{version}/simbeamd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "13104977e5c120e4ca20263c34c26542ea9898b683abe30d884f8862c41fc999"
      url "https://github.com/kei-sidorov/simbeam/releases/download/v#{version}/simbeamd_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "simbeamd"
  desc "simbeam daemon — stream an iOS simulator from Mac to iPad"
  homepage "https://github.com/kei-sidorov/simbeam"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "kei-sidorov/simbeam/simbeam-control",
    ]

  binary "simbeamd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/simbeamd"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    simbeamd is shipped as an unsigned binary. The cask's post-install hook
    strips the macOS quarantine attribute so Gatekeeper should not block it.
    simbeamd drives simulators through simbeam-control (needs a full Xcode);
    idb_companion and ffmpeg are no longer required.
  EOS
end
