# This file was generated by GoReleaser. DO NOT EDIT.
cask "simcastd" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "f96d2c2fb8c7ee4bd7134f61f5141803cd794107d14987c68375a06760d0d279"
      url "https://github.com/kei-sidorov/simcast/releases/download/v#{version}/simcastd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "404c8e8200b85ae809458974991be256160f46e069d6e69112efa1be6fc4da92"
      url "https://github.com/kei-sidorov/simcast/releases/download/v#{version}/simcastd_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "simcastd"
  desc "simcast daemon — stream an iOS simulator from Mac to iPad"
  homepage "https://github.com/kei-sidorov/simcast"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
      "idb-companion",
    ]

  binary "simcastd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/simcastd"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    simcastd is shipped as an unsigned binary. The cask's post-install hook
    strips the macOS quarantine attribute so Gatekeeper should not block it.
    simcastd shells out to idb_companion (simulators) and ffmpeg (h264_videotoolbox).
  EOS
end
