# This file was generated by GoReleaser. DO NOT EDIT.
cask "simcastd" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "0e7eae6620e64d52281a84b10c06247c20093a58a57a010a10bc55ab46fc189b"
      url "https://github.com/kei-sidorov/simcast/releases/download/v#{version}/simcastd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "46821efffa9846d058dabea9b192e98bc337ee648c413ae0e2a668e4c55c54c3"
      url "https://github.com/kei-sidorov/simcast/releases/download/v#{version}/simcastd_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "simcastd"
  desc "simcast daemon — stream an iOS simulator from Mac to iPad"
  homepage "https://github.com/kei-sidorov/simcast"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
      "idb-companion",
    ]

  binary "simcastd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/simcastd"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    simcastd is shipped as an unsigned binary. The cask's post-install hook
    strips the macOS quarantine attribute so Gatekeeper should not block it.
    simcastd shells out to idb_companion (simulators) and ffmpeg (h264_videotoolbox).
  EOS
end
