# This file was generated by GoReleaser. DO NOT EDIT.
cask "simcastd" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "f6792699d3a3e1bc3fe73aaf916ae4026edf6128b2e3bd1ef723fb1002f6c79b"
      url "https://github.com/kei-sidorov/simcast/releases/download/v#{version}/simcastd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c7c28953bf50535ee649153e515c1aaab8f323edcb3ab7363be7d4851011acbb"
      url "https://github.com/kei-sidorov/simcast/releases/download/v#{version}/simcastd_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "simcastd"
  desc "simcast daemon — stream an iOS simulator from Mac to iPad"
  homepage "https://github.com/kei-sidorov/simcast"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
      "idb-companion",
    ]

  binary "simcastd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/simcastd"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    simcastd is shipped as an unsigned binary. The cask's post-install hook
    strips the macOS quarantine attribute so Gatekeeper should not block it.
    simcastd shells out to idb_companion (simulators) and ffmpeg (h264_videotoolbox).
  EOS
end
